---
title: "DataViz Project Requirements"
author: "Fall 2016"
output:
  html_document:
    keep_md: yes
  pdf_document: default
---

## Requirements

+ Work in groups of 2-3

+ You may use data from the internet, data that you've collected yourself, or data that you may have used for another class. However, this project is meant to be different than anything you've done before.

## Skills

+ RMarkdown

+ Data cleaning and (possibly) data manipulation

+ Data visualization

+ Assessment of data visualizations

## Deadlines

+ Proposal 11/30 - a one page introduction which (i) explores your question(s) of interest, (ii) a **brief** literature review in which you summarize the work done of others, (ii) an explanation of your data, including a description of each variable and the sample size and (iv) who your work will generalize too (i.e, why should *other* people be interested in this work).

+ Presentations 12/14 - we do these on the last day of class

+ Technical reports 12/20 - due at midnight at december 19th. This will be a continuation of your proposals to include your graphics and conclusions

## Presentation details

+  Each group member must be present

+  Each group member must discuss at least two graphics

+  Each group will have 10 minutes to present, plus 5 minutes of questions and answers with the audience

+  Your presentation grade will be graded based on how well you work as a group and describe your data during their presentation.  For example, transitions between graphs, group members, etc should be smooth.  Individuals should refer to other graphics presented by other members of their group when appropriate.


## Project details

+ 5-6 high quality plots. Six plots required for groups of three. You'll print these in advance and hand to the class before the presentation. You may also use interactive plots. 

+ At least 4 of the plots need to include at least 2 variables

+  You are **strongly encouraged** to try new graphics that we didn't cover in class!


## Evaluation of presentation 

+ Creativity (in design)

+ Visualization details

+ Depth/appropriateness of visualization

+ Accuracy of presentation

+ Presentation (volume, presence, eye contact, etc) 


## Report details

1. Introduction (1 page). Why is your problem important? What other work has been done? Why are your questions of interest actually interesting? What does your data look like? Where does it come from? How was it obtained? What are the variable types and units? What were the steps you took in cleaning the data?

2. Descriptions of visualizations (page length will vary). 

A summary of each graphic should contain

+  the graphic itself (or an example version of the graphic if the graphic is interactive)
+  one paragraph (3-5 sentences) summarizing the key takeaways of graphic and any interesting features / associations / relationships / etc that the user should understand
+  one paragraph (3-5 sentences) describing the tools used to create the graphic (e.g. `ggplot` features, other plotting tools, etc), the coding techniques necessary to manipulate the data in order to create the graphic (e.g. subsetting, etc), and any graphical choices that were made (e.g. bandwidth / bin width choices, etc)

3. Conclusions (1 page). Practical findings and conclusions. Weaknesses in design. Other variables that you'd want to look at?


This is a formal report.  Your writing should be professional and free of spelling/grammar errors.  Your graphs should be high-quality, with titles, axis labels, legends, etc.



## Notes

+ You should show **all** code for your technical report, but that your report to the class should only show code where needed (e.g., if you are doing something new)

+ Please cite your sources, either using traditional format (Lopez, 2013) or links to URLs. See the Markdown cheatsheet for how to use URLs in Markdown. 

+ Consider the project requirements when thinking about what data you'd like to use. If you have a data set with 2 or 3 variables, it is likely insufficient for meeting the requirements above. However, you can certainly merge existing data sets together (which I can help with).

+ Each group should submit a single .Rmd file and a single .html file containing their report. Each group should submit one report only.

+ One grade will be awarded to the entire group, although your professor reserves the rate to change group grades if individual participation varies. 

+ Come up with a clever group name! It will make it easier for me to identify you as a group. 
